/***************************************************************************

   Program:    AMPlot2
   File:       interface.h
   
   Version:    V1.0
   Date:       12.03.92
   Function:   External definitions of menus, gadgets, etc.
   
   Copyright:  SciTech Software 1992
   Author:     Dr. Andrew C. R. Martin
   Address:    SciTech Software
               23, Stag Leys,
               Ashtead,
               Surrey,
               KT21 2TD.
   Phone:      +44 (0372) 275775
   EMail:      UUCP: cbmuk!cbmuka!scitec!amartin
               JANET: andrew@uk.ac.ox.biop
               
****************************************************************************

   This program is copyright. Any copying without the permission of
   SciTech Software is illegal.

****************************************************************************

   Description:
   ============

****************************************************************************

   Usage:
   ======

****************************************************************************

   Revision History:
   =================

***************************************************************************/


#ifdef MAIN
struct Menu          *ProjectMenu   = NULL,
                     *StyleMenu     = NULL,
                     *AxesMenu      = NULL,
                     *TextMenu      = NULL,
                     *LinesMenu     = NULL,
                     *FitMenu       = NULL,
                     *RexxMenu      = NULL;

struct MenuItem      *MenuOpen      = NULL,
                     *MenuSave      = NULL,
                     *MenuSaveAs    = NULL,
                     *MenuEdit      = NULL,
                     *MenuPlot      = NULL,
                     *MenuPaper     = NULL,
                     *MenuSetPens   = NULL,
                     *MenuAbout     = NULL,
                     *MenuQuit      = NULL,
                     *MenuPS        = NULL,
                     *MenuHPGL      = NULL,
                     *MenuDR2D      = NULL,
                     *MenuXY        = NULL,
                     *MenuScatter   = NULL,
                     *MenuBar       = NULL,
                     *MenuPie       = NULL,
                     *MenuErrors    = NULL,
                     *MenuEject     = NULL,
                     *MenuLineSet   = NULL,
                     *MenuBarSet    = NULL,
                     *MenuPieSet    = NULL,
                     *MenuLogX      = NULL,
                     *MenuLogY      = NULL,
                     *MenuBoxed     = NULL,
                     *MenuGrid      = NULL,
                     *MenuAxes      = NULL,
                     *MenuFZero     = NULL,
                     *MenuTitle     = NULL,
                     *MenuAxTitle   = NULL,
                     *MenuAxLabel   = NULL,
                     *MenuKey       = NULL,
                     *MenuLabel     = NULL,
                     *MenuPen       = NULL,
                     *MenuStyle     = NULL,
                     *MenuFills     = NULL,
                     *MenuFillType  = NULL,
                     *MenuRegress   = NULL,
                     *MenuRobust    = NULL,
                     *MenuFourier   = NULL,
                     *MenuRexxFit   = NULL,
                     *MenuRexx      = NULL,
                     *MenuRunRexx   = NULL,
                     *MenuDebRexx   = NULL,
                     *MenuLS1       = NULL,
                     *MenuLS2       = NULL,
                     *MenuLS3       = NULL,
                     *MenuLS4       = NULL,
                     *MenuLS5       = NULL,
                     *MenuLS6       = NULL,
                     *MenuFT1       = NULL,
                     *MenuFT2       = NULL,
                     *MenuFT3       = NULL,
                     *MenuFT4       = NULL,
                     *MenuFT5       = NULL,
                     *MenuFT6       = NULL,
                     *MenuPalette   = NULL,
                     *MenuScrBack   = NULL,
                     *MenuNoFills   = NULL;
                     
struct NewWindow     *NWPaper       = NULL,
                     *NWSetPens     = NULL,
                     *NWLineStyle   = NULL,
                     *NWBarStyle    = NULL,
                     *NWPieStyle    = NULL,
                     *NWSetAxes     = NULL,
                     *NWAxisTitles  = NULL,
                     *NWTitle       = NULL,
                     *NWAxisLabels  = NULL,
                     *NWExtraLabels = NULL,
                     *NWKey         = NULL,
                     *NWRegression  = NULL,
                     *NWRexxFit     = NULL,
                     *NWFourier     = NULL,
                     *NWBarLabels   = NULL,
                     *NWAbout       = NULL,
                     *NWPen         = NULL,
                     *NWFill        = NULL,
                     *NWPieLab      = NULL;

struct Gadget     *PaperEPSF        = NULL,
                  *PaperOK          = NULL,
                  *PaperCancel      = NULL,
                  *SetPensOK        = NULL,
                  *SetPensCancel    = NULL,
                  *SetAxesOK        = NULL,
                  *SetAxesCancel    = NULL,
                  *BoundsXMin       = NULL,
                  *BoundsXMax       = NULL,
                  *BoundsYMin       = NULL,
                  *BoundsYMax       = NULL,
                  *TicksX           = NULL,
                  *TicksY           = NULL,
                  *TicksXSub        = NULL,
                  *TicksYSub        = NULL,
                  *BarStyleOK       = NULL,
                  *BarStyleCancel   = NULL,
                  *BarStyleShrink   = NULL,
                  *BarStyleFillAll  = NULL,
                  *BarStyle3D       = NULL,
                  *BarStyles[5],
                  *BoundsAuto       = NULL,
                  *TicksAuto        = NULL,
                  *BoundsClip       = NULL,
                  *TicksSub         = NULL,
                  *PieStyleOK       = NULL,
                  *PieStyleCancel   = NULL,
                  *PieStyle3D       = NULL,
                  *AxisTitleOK      = NULL,
                  *AxisTitleCancel  = NULL,
                  *XTitleGadget     = NULL,
                  *TitleOK          = NULL,
                  *TitleCancel      = NULL,
                  *TitleCentre      = NULL,
                  *TitlePosX        = NULL,
                  *TitlePosY        = NULL,
                  *TitleText        = NULL,
                  *AxisLabelsOK     = NULL,
                  *AxisLabelsCancel = NULL,
                  *AxLabNoX         = NULL,
                  *AxLabNoY         = NULL,
                  *AxLabCentreX     = NULL,
                  *AxLabBarLabels   = NULL,
                  *AxLabXPrec       = NULL,
                  *AxLabYPrec       = NULL,
                  *ExtraLabelsOK    = NULL,
                  *ExtraLabelsKillAll= NULL,
                  *LabelPrev        = NULL,
                  *LabelNext        = NULL,
                  *LabelKill        = NULL,
                  *LabelText        = NULL,
                  *LabelPosX        = NULL,
                  *LabelPosY        = NULL,
                  *RegressionOK     = NULL,
                  *RegressionCancel = NULL,
                  *RegressionWrite  = NULL,
                  *RegressionOff    = NULL,
                  *RexxFitOK        = NULL,
                  *RexxFitCancel    = NULL,
                  *RexxFitFiles     = NULL,
                  *RexxFitOff       = NULL,
                  *RexxFitFName     = NULL,
                  *RexxFitWrite     = NULL,
                  *KeyOK            = NULL,
                  *KeyCancel        = NULL,
                  *KeyPrev          = NULL,
                  *KeyNext          = NULL,
                  *KeyRemove        = NULL,
                  *KeyDataset       = NULL,
                  *KeyText          = NULL,
                  *KeyXPos          = NULL,
                  *KeyYPos          = NULL,
                  *FourierOK        = NULL,
                  *FourierCancel    = NULL,
                  *FourierOff       = NULL,
                  *BarLabOK         = NULL,
                  *BarLabRemove     = NULL,
                  *BarLabPrev       = NULL,
                  *BarLabNext       = NULL,
                  *BarLabText       = NULL,
                  *BarLabNum        = NULL,
                  *LineStyleOK      = NULL,
                  *LineStyleCancel  = NULL,
                  *Pen1DP[14],
                  *Pen2DP[14],
                  *Pen3DP[14],
                  *Pen4DP[14],
                  *Pen5DP[14],
                  *Pen6DP[14],
                  *Pen1Link         = NULL,
                  *Pen2Link         = NULL,
                  *Pen3Link         = NULL,
                  *Pen4Link         = NULL,
                  *Pen5Link         = NULL,
                  *Pen6Link         = NULL,
                  *AboutOK          = NULL,
                  *PenOK            = NULL,
                  *PenCancel        = NULL,
                  *PenNumGadget     = NULL,
                  *FillOK           = NULL,
                  *FillCancel       = NULL,
                  *FillStyle[3],
                  *PieLabelsOK      = NULL,
                  *PieLabelsKillAll = NULL,
                  *PieLabPrev       = NULL,
                  *PieLabNext       = NULL,
                  *PieLabKill       = NULL,
                  *PieLabText       = NULL,
                  *PieLabAngle      = NULL,
                  *PieLabDist       = NULL;
                  

char              PaperXSizeBuff[NUMBUFF],
                  PaperYSizeBuff[NUMBUFF],
                  PaperXOffBuff[NUMBUFF],
                  PaperYOffBuff[NUMBUFF],
                  SetPen1ColBuff[NUMBUFF],
                  SetPen2ColBuff[NUMBUFF],
                  SetPen3ColBuff[NUMBUFF],
                  SetPen4ColBuff[NUMBUFF],
                  SetPen5ColBuff[NUMBUFF],
                  SetPen6ColBuff[NUMBUFF],
                  SetPen1ThickBuff[NUMBUFF],
                  SetPen2ThickBuff[NUMBUFF],
                  SetPen3ThickBuff[NUMBUFF],
                  SetPen4ThickBuff[NUMBUFF],
                  SetPen5ThickBuff[NUMBUFF],
                  SetPen6ThickBuff[NUMBUFF],
                  BarShrinkBuff[NUMBUFF],
                  BoundsXMinBuff[NUMBUFF],
                  BoundsXMaxBuff[NUMBUFF],
                  BoundsYMinBuff[NUMBUFF],
                  BoundsYMaxBuff[NUMBUFF],
                  TickXBuff[NUMBUFF],
                  SubXBuff[NUMBUFF],
                  TickYBuff[NUMBUFF],
                  SubYBuff[NUMBUFF],
                  PieStartBuff[NUMBUFF],
                  PieEjectBuff[NUMBUFF],
                  XTitleTextBuff[MAXBUFF],
                  YTitleTextBuff[MAXBUFF],
                  XTitleFontBuff[MAXBUFF],
                  YTitleFontBuff[MAXBUFF],
                  XTitleSizeBuff[NUMBUFF],
                  YTitleSizeBuff[NUMBUFF],
                  TitleTextBuff[MAXBUFF],
                  TitleFontBuff[MAXBUFF],
                  TitleSizeBuff[NUMBUFF],
                  TitlePosXBuff[NUMBUFF],
                  TitlePosYBuff[NUMBUFF],
                  AxLabXFontBuff[MAXBUFF],
                  AxLabXSizeBuff[NUMBUFF],
                  AxLabXPrecBuff[NUMBUFF],
                  AxLabYFontBuff[MAXBUFF],
                  AxLabYSizeBuff[NUMBUFF],
                  AxLabYPrecBuff[NUMBUFF],
                  LabelTextBuff[MAXBUFF],
                  LabelFontBuff[MAXBUFF],
                  LabelSizeBuff[NUMBUFF],
                  LabelPosXBuff[NUMBUFF],
                  LabelPosYBuff[NUMBUFF],
                  RegressDegreeBuff[NUMBUFF],
                  RegressTolBuff[NUMBUFF],
                  RexxFitDegreeBuff[NUMBUFF],
                  RexxFitTolBuff[NUMBUFF],
                  KeyTextBuff[MAXBUFF],
                  KeyFontBuff[MAXBUFF],
                  KeySizeBuff[NUMBUFF],
                  KeyPosXBuff[NUMBUFF],
                  KeyPosYBuff[NUMBUFF],
                  KeyDatasetBuff[NUMBUFF],
                  FourierBuff[NUMBUFF],
                  BarLabTextBuff[MAXBUFF],
                  BarLabNumBuff[NUMBUFF],
                  LineStyleEBarBuff[NUMBUFF],
                  LineStyleDPSizeBuff[NUMBUFF],
                  PenNumberBuff[NUMBUFF],
                  FillHatchThickBuff[NUMBUFF],
                  FillHatchSpaceBuff[NUMBUFF],
                  PieLabTextBuff[MAXBUFF],
                  PieLabFontBuff[MAXBUFF],
                  PieLabSizeBuff[NUMBUFF],
                  PieLabAngleBuff[NUMBUFF],
                  PieLabDistBuff[NUMBUFF];


#else /*********************************************************************/

extern struct Menu      *ProjectMenu,
                        *StyleMenu,
                        *AxesMenu,
                        *TextMenu,
                        *LinesMenu,
                        *FitMenu,
                        *RexxMenu;

extern struct MenuItem  *MenuOpen,
                        *MenuSave,
                        *MenuSaveAs,
                        *MenuEdit,
                        *MenuPlot,
                        *MenuPaper,
                        *MenuSetPens,
                        *MenuAbout,
                        *MenuQuit,
                        *MenuPS,
                        *MenuHPGL,
                        *MenuDR2D,
                        *MenuXY,
                        *MenuScatter,
                        *MenuBar,
                        *MenuPie,
                        *MenuErrors,
                        *MenuEject,
                        *MenuLineSet,
                        *MenuBarSet,
                        *MenuPieSet,
                        *MenuLogX,
                        *MenuLogY,
                        *MenuBoxed,
                        *MenuGrid,
                        *MenuAxes,
                        *MenuFZero,
                        *MenuTitle,
                        *MenuAxTitle,
                        *MenuAxLabel,
                        *MenuKey,
                        *MenuLabel,
                        *MenuPen,
                        *MenuStyle,
                        *MenuFills,
                        *MenuFillType,
                        *MenuRegress,
                        *MenuRobust,
                        *MenuFourier,
                        *MenuRexxFit,
                        *MenuRexx,
                        *MenuRunRexx,
                        *MenuDebRexx,
                        *MenuLS1,
                        *MenuLS2,
                        *MenuLS3,
                        *MenuLS4,
                        *MenuLS5,
                        *MenuLS6,
                        *MenuFT1,
                        *MenuFT2,
                        *MenuFT3,
                        *MenuFT4,
                        *MenuFT5,
                        *MenuFT6,
                        *MenuPalette,
                        *MenuScrBack,
                        *MenuNoFills;
                     
extern struct NewWindow *NWPaper,
                        *NWSetPens,
                        *NWLineStyle,
                        *NWBarStyle,
                        *NWPieStyle,
                        *NWSetAxes,
                        *NWAxisTitles,
                        *NWTitle,
                        *NWAxisLabels,
                        *NWExtraLabels,
                        *NWKey,
                        *NWRegression,
                        *NWRexxFit,
                        *NWFourier,
                        *NWBarLabels,
                        *NWAbout,
                        *NWPen,
                        *NWFill,
                        *NWPieLab;

extern struct Gadget    *PaperEPSF,
                        *PaperOK,
                        *PaperCancel,
                        *SetPensOK,
                        *SetPensCancel,
                        *SetAxesOK,
                        *SetAxesCancel,
                        *BoundsXMin,
                        *BoundsXMax,
                        *BoundsYMin,
                        *BoundsYMax,
                        *TicksX,
                        *TicksY,
                        *TicksXSub,
                        *TicksYSub,
                        *BarStyleOK,
                        *BarStyleCancel,
                        *BarStyleShrink,
                        *BarStyleFillAll,
                        *BarStyle3D,
                        *BarStyles[5],
                        *BoundsAuto,
                        *TicksAuto,
                        *BoundsClip,
                        *TicksSub,
                        *PieStyleOK,
                        *PieStyleCancel,
                        *PieStyle3D,
                        *AxisTitleOK,
                        *AxisTitleCancel,
                        *XTitleGadget,
                        *TitleOK,
                        *TitleCancel,
                        *TitleCentre,
                        *TitlePosX,
                        *TitlePosY,
                        *TitleText,
                        *AxisLabelsOK,
                        *AxisLabelsCancel,
                        *AxLabNoX,
                        *AxLabNoY,
                        *AxLabCentreX,
                        *AxLabBarLabels,
                        *AxLabXPrec,
                        *AxLabYPrec,
                        *ExtraLabelsOK,
                        *ExtraLabelsKillAll,
                        *LabelPrev,
                        *LabelNext,
                        *LabelKill,
                        *LabelText,
                        *LabelPosX,
                        *LabelPosY,
                        *RegressionOK,
                        *RegressionCancel,
                        *RegressionWrite,
                        *RegressionOff,
                        *RexxFitOK,
                        *RexxFitCancel,
                        *RexxFitFiles,
                        *RexxFitOff,
                        *RexxFitFName,
                        *RexxFitWrite,
                        *KeyOK,
                        *KeyCancel,
                        *KeyPrev,
                        *KeyNext,
                        *KeyRemove,
                        *KeyDataset,
                        *KeyText,
                        *KeyXPos,
                        *KeyYPos,
                        *FourierOK,
                        *FourierCancel,
                        *FourierOff,
                        *BarLabOK,
                        *BarLabRemove,
                        *BarLabPrev,
                        *BarLabNext,
                        *BarLabText,
                        *BarLabNum,
                        *LineStyleOK,
                        *LineStyleCancel,
                        *Pen1DP[14],
                        *Pen2DP[14],
                        *Pen3DP[14],
                        *Pen4DP[14],
                        *Pen5DP[14],
                        *Pen6DP[14],
                        *Pen1Link,
                        *Pen2Link,
                        *Pen3Link,
                        *Pen4Link,
                        *Pen5Link,
                        *Pen6Link,
                        *AboutOK,
                        *PenOK,
                        *PenCancel,
                        *PenNumGadget,
                        *FillOK,
                        *FillCancel,
                        *FillStyle[3],
                        *PieLabelsOK,
                        *PieLabelsKillAll,
                        *PieLabPrev,
                        *PieLabNext,
                        *PieLabKill,
                        *PieLabText,
                        *PieLabAngle,
                        *PieLabDist;

extern char             PaperXSizeBuff[NUMBUFF],
                        PaperYSizeBuff[NUMBUFF],
                        PaperXOffBuff[NUMBUFF],
                        PaperYOffBuff[NUMBUFF],
                        SetPen1ColBuff[NUMBUFF],
                        SetPen2ColBuff[NUMBUFF],
                        SetPen3ColBuff[NUMBUFF],
                        SetPen4ColBuff[NUMBUFF],
                        SetPen5ColBuff[NUMBUFF],
                        SetPen6ColBuff[NUMBUFF],
                        SetPen1ThickBuff[NUMBUFF],
                        SetPen2ThickBuff[NUMBUFF],
                        SetPen3ThickBuff[NUMBUFF],
                        SetPen4ThickBuff[NUMBUFF],
                        SetPen5ThickBuff[NUMBUFF],
                        SetPen6ThickBuff[NUMBUFF],
                        BarShrinkBuff[NUMBUFF],
                        BoundsXMinBuff[NUMBUFF],
                        BoundsXMaxBuff[NUMBUFF],
                        BoundsYMinBuff[NUMBUFF],
                        BoundsYMaxBuff[NUMBUFF],
                        TickXBuff[NUMBUFF],
                        SubXBuff[NUMBUFF],
                        TickYBuff[NUMBUFF],
                        SubYBuff[NUMBUFF],
                        PieStartBuff[NUMBUFF],
                        PieEjectBuff[NUMBUFF],
                        XTitleTextBuff[MAXBUFF],
                        YTitleTextBuff[MAXBUFF],
                        XTitleFontBuff[MAXBUFF],
                        YTitleFontBuff[MAXBUFF],
                        XTitleSizeBuff[NUMBUFF],
                        YTitleSizeBuff[NUMBUFF],
                        TitleTextBuff[MAXBUFF],
                        TitleFontBuff[MAXBUFF],
                        TitleSizeBuff[NUMBUFF],
                        TitlePosXBuff[NUMBUFF],
                        TitlePosYBuff[NUMBUFF],
                        AxLabXFontBuff[MAXBUFF],
                        AxLabXSizeBuff[NUMBUFF],
                        AxLabXPrecBuff[NUMBUFF],
                        AxLabYFontBuff[MAXBUFF],
                        AxLabYSizeBuff[NUMBUFF],
                        AxLabYPrecBuff[NUMBUFF],
                        LabelTextBuff[MAXBUFF],
                        LabelFontBuff[MAXBUFF],
                        LabelSizeBuff[NUMBUFF],
                        LabelPosXBuff[NUMBUFF],
                        LabelPosYBuff[NUMBUFF],
                        RegressDegreeBuff[NUMBUFF],
                        RegressTolBuff[NUMBUFF],
                        RexxFitDegreeBuff[NUMBUFF],
                        RexxFitTolBuff[NUMBUFF],
                        KeyTextBuff[MAXBUFF],
                        KeyFontBuff[MAXBUFF],
                        KeySizeBuff[NUMBUFF],
                        KeyPosXBuff[NUMBUFF],
                        KeyPosYBuff[NUMBUFF],
                        KeyDatasetBuff[NUMBUFF],
                        FourierBuff[NUMBUFF],
                        BarLabTextBuff[MAXBUFF],
                        BarLabNumBuff[NUMBUFF],
                        LineStyleEBarBuff[NUMBUFF],
                        LineStyleDPSizeBuff[NUMBUFF],
                        PenNumberBuff[NUMBUFF],
                        FillHatchThickBuff[NUMBUFF],
                        FillHatchSpaceBuff[NUMBUFF],
                        PieLabTextBuff[MAXBUFF],
                        PieLabFontBuff[MAXBUFF],
                        PieLabSizeBuff[NUMBUFF],
                        PieLabAngleBuff[NUMBUFF],
                        PieLabDistBuff[NUMBUFF];

#endif
